/**
 * Product Data English Translation Module
 * Translates Russian product names, categories, attributes to professional English
 */

// Category translations
export const CATEGORY_TRANSLATIONS: Record<string, string> = {
  'Контроллеры полета': 'Flight Controllers',
  'Полётные контроллеры': 'Flight Controllers',
  'Моторы': 'Motors',
  'Бесколлекторные моторы': 'Brushless Motors',
  'Моторы для FPV': 'FPV Motors',
  'Регуляторы скорости': 'ESCs',
  'Регуляторы хода': 'ESCs',
  'Пропеллеры': 'Propellers',
  'Пропы': 'Propellers',
  'Лопасти': 'Blades',
  'Рамы': 'Frames',
  'Каркасы': 'Frames',
  'Рамы для коптеров': 'Drone Frames',
  'Аккумуляторы': 'Batteries',
  'LiPo аккумуляторы': 'LiPo Batteries',
  'Батареи': 'Batteries',
  'FPV системы': 'FPV Systems',
  'Камеры FPV': 'FPV Cameras',
  'Видеопередатчики': 'Video Transmitters',
  'VTX': 'VTX',
  'Очки FPV': 'FPV Goggles',
  'Антенны': 'Antennas',
  'Приемники': 'Receivers',
  'Передатчики': 'Transmitters',
  'Радиоаппаратура': 'Radio Systems',
  'GPS модули': 'GPS Modules',
  'Компасы': 'Compasses',
  'Дроны': 'Drones',
  'Квадрокоптеры': 'Quadcopters',
  'Мультикоптеры': 'Multirotors',
  'RTF': 'RTF',
  'Готовые решения': 'Ready-to-Fly',
  'Промышленные дроны': 'Industrial Drones',
  'Профессиональные дроны': 'Professional Drones',
  'Для съемки': 'Aerial Photography',
  'Для картографии': 'Mapping & Surveying',
  'Для инспекций': 'Inspection Drones',
  'Сельскохозяйственные': 'Agricultural Drones',
  'Грузовые': 'Cargo Drones',
  'Аксессуары': 'Accessories',
  'Комплектующие': 'Components',
  'Запчасти': 'Spare Parts',
  'Провода': 'Wires & Cables',
  'Разъемы': 'Connectors',
  'Крепеж': 'Fasteners',
  '3D печать': '3D Printed Parts',
  'Инструменты': 'Tools',
  'Паяльное оборудование': 'Soldering Equipment',
  'Зарядные устройства': 'Chargers',
  'Камеры': 'Cameras',
  'Подвесы': 'Gimbals',
  'Стабилизаторы': 'Stabilizers',
  'Датчики': 'Sensors',
  'Шасси': 'Landing Gear',
  'Посадочные площадки': 'Landing Pads',
  'Специализированные': 'Specialized',
  'Для предприятий': 'For Enterprises',
  'Тепловизионные дроны': 'Thermal Imaging Drones',
}

// Attribute name translations
export const ATTRIBUTE_TRANSLATIONS: Record<string, string> = {
  'Размер': 'Size',
  'KV': 'KV Rating',
  'Количество витков': 'Stator Size',
  'Вес': 'Weight',
  'Максимальный ток': 'Max Current',
  'Напряжение': 'Voltage',
  'Диаметр вала': 'Shaft Diameter',
  'Конфигурация': 'Configuration',
  'Емкость': 'Capacity',
  'Количество банок': 'Cell Count',
  'Токоотдача': 'Discharge Rate',
  'Разъем': 'Connector',
  'Химический состав': 'Chemistry',
  'Ток': 'Current Rating',
  'Постоянный ток': 'Continuous Current',
  'Пиковый ток': 'Burst Current',
  'Поддержка DShot': 'DShot Support',
  'Прошивка': 'Firmware',
  'BEC': 'BEC Output',
  'Диаметр': 'Diameter',
  'Шаг': 'Pitch',
  'Материал': 'Material',
  'Количество лопастей': 'Blade Count',
  'Цвет': 'Color',
  'Направление': 'Rotation',
  'Колесная база': 'Wheelbase',
  'Материал рамы': 'Frame Material',
  'Толщина пластины': 'Plate Thickness',
  'Совместимость': 'Compatibility',
  'Разрешение': 'Resolution',
  'Сенсор': 'Sensor',
  'Угол обзора': 'Field of View',
  'Формат': 'Aspect Ratio',
  'TVL': 'TVL',
  'Ночная съемка': 'Night Vision',
  'Мощность': 'Output Power',
  'Частота': 'Frequency',
  'Каналы': 'Channels',
  'Дальность': 'Range',
  'SmartAudio': 'SmartAudio',
  'Протокол': 'Protocol',
  'Частотный диапазон': 'Frequency Band',
  'Количество каналов': 'Channel Count',
  'Модуляция': 'Modulation',
  'Производитель': 'Manufacturer',
  'Бренд': 'Brand',
  'Модель': 'Model',
  'Состояние': 'Condition',
  'Гарантия': 'Warranty',
  'Страна производства': 'Country of Origin',
  'Тип': 'Type',
  'Применение': 'Application',
  'Длина': 'Length',
  'Ширина': 'Width',
  'Высота': 'Height',
  'Длина кабеля': 'Cable Length',
  'Интерфейс': 'Interface',
  'Версия': 'Version',
}

// Attribute value translations
export const ATTRIBUTE_VALUE_TRANSLATIONS: Record<string, string> = {
  'Карбон': 'Carbon Fiber',
  'Углеродное волокно': 'Carbon Fiber',
  'Пластик': 'Plastic',
  'Алюминий': 'Aluminum',
  'Металл': 'Metal',
  'Стекловолокно': 'Fiberglass',
  'Нейлон': 'Nylon',
  'Поликарбонат': 'Polycarbonate',
  'Прямое': 'CW',
  'Обратное': 'CCW',
  'По часовой': 'CW',
  'Против часовой': 'CCW',
  'Черный': 'Black',
  'Белый': 'White',
  'Красный': 'Red',
  'Синий': 'Blue',
  'Зеленый': 'Green',
  'Желтый': 'Yellow',
  'Серый': 'Gray',
  'Оранжевый': 'Orange',
  'Прозрачный': 'Clear',
  'Новый': 'New',
  'Б/у': 'Used',
  'LiPo': 'LiPo',
  'Li-ion': 'Li-ion',
  'LiHV': 'LiHV',
  'Да': 'Yes',
  'Нет': 'No',
  'Есть': 'Yes',
  'Отсутствует': 'No',
  'Betaflight': 'Betaflight',
  'INAV': 'INAV',
  'ArduPilot': 'ArduPilot',
  'PX4': 'PX4',
  'BLHeli_S': 'BLHeli_S',
  'BLHeli_32': 'BLHeli_32',
  'SBUS': 'SBUS',
  'IBUS': 'IBUS',
  'PPM': 'PPM',
  'Crossfire': 'Crossfire',
  'ELRS': 'ExpressLRS',
}

// Technical term dictionary
const TECH_TERMS: Record<string, string> = {
  'полетный контроллер': 'flight controller',
  'контроллер полета': 'flight controller',
  'бесколлекторный мотор': 'brushless motor',
  'бк мотор': 'brushless motor',
  'регулятор скорости': 'ESC',
  'регулятор хода': 'ESC',
  'пропеллер': 'propeller',
  'лопасть': 'blade',
  'рама': 'frame',
  'аккумулятор': 'battery',
  'липошка': 'LiPo battery',
  'акб': 'battery',
  'fpv камера': 'FPV camera',
  'видеопередатчик': 'video transmitter',
  'видео приемник': 'video receiver',
  'очки': 'goggles',
  'антенна': 'antenna',
  'приемник': 'receiver',
  'передатчик': 'transmitter',
  'аппаратура': 'radio',
  'пульт': 'radio controller',
  'gps модуль': 'GPS module',
  'компас': 'compass',
  'подвес': 'gimbal',
  'стабилизатор': 'stabilizer',
  'дрон': 'drone',
  'квадрокоптер': 'quadcopter',
  'коптер': 'copter',
  'мультикоптер': 'multirotor',
  'гексакоптер': 'hexacopter',
  'октокоптер': 'octocopter',
  'бесколлекторный': 'brushless',
  'разъем': 'connector',
  'провод': 'wire',
  'кабель': 'cable',
  '3д печать': '3D printed',
  'напечатанный': 'printed',
  'паяльник': 'soldering iron',
  'зарядное устройство': 'charger',
  'зарядка': 'charger',
  'болт': 'bolt',
  'винт': 'screw',
  'гайка': 'nut',
  'шайба': 'washer',
  'стойка': 'standoff',
  'хомут': 'zip tie',
  'запчасть': 'spare part',
  'комплект': 'kit',
  'набор': 'set',
  'пара': 'pair',
  'штука': 'piece',
  'для': 'for',
  'с': 'with',
  'без': 'without',
  'и': 'and',
  'в': 'in',
  'на': 'on',
  'новый': 'new',
  'оригинал': 'original',
  'оригинальный': 'original',
  'профессиональный': 'professional',
  'высококачественный': 'high-quality',
  'прочный': 'durable',
  'легкий': 'lightweight',
  'мощный': 'powerful',
  'высокоскоростной': 'high-speed',
  'мини': 'mini',
  'микро': 'micro',
  'большой': 'large',
  'маленький': 'small',
  'длинный': 'long',
  'короткий': 'short',
  'толстый': 'thick',
  'тонкий': 'thin',
  'левый': 'left',
  'правый': 'right',
  'передний': 'front',
  'задний': 'rear',
  'верхний': 'upper',
  'нижний': 'lower',
  'внутренний': 'inner',
  'внешний': 'outer',
  'черный': 'black',
  'белый': 'white',
  'красный': 'red',
  'синий': 'blue',
  'зеленый': 'green',
  'желтый': 'yellow',
  'серый': 'gray',
  'прозрачный': 'clear',
}

/**
 * Translate a Russian product name to professional English
 */
export function translateProductName(name: string): string {
  if (!name) return name
  let result = name

  // Replace technical terms (longer phrases first to avoid partial matches)
  const sortedTerms = Object.entries(ALL_TERMS).sort((a, b) => b[0].length - a[0].length)
  for (const [ru, en] of sortedTerms) {
    const escaped = ru.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const regex = new RegExp(`(?<![a-zA-Zа-яА-Я])${escaped}(?![a-zA-Zа-яА-Я])`, 'gi')
    result = result.replace(regex, en)
  }

  // Clean up extra spaces
  result = result.replace(/\s+/g, ' ').trim()

  // Capitalize properly
  result = result.split(' ').map(word => {
    if (!word) return word
    const lower = word.toLowerCase()
    if (['for', 'with', 'and', 'in', 'on', 'to', 'of', 'the', 'a', 'an'].includes(lower)) {
      return lower
    }
    // Keep technical abbreviations uppercase
    if (/^(ESC|VTX|VRX|FC|BEC|DShot|SBUS|PPM|GPS|FPV|RTF|LiPo|LiHV|XT60|XT90|JST|CCW|CW|KV|TVL|RTK|DJI|HD|4K|8K|UHD|FHD|HDMI|USB|SD|LED|OSD|UART|I2C|SPI|PWM|CAN)$/i.test(word)) {
      return word.toUpperCase()
    }
    return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
  }).join(' ')

  return result
}

export function translateCategoryName(name: string): string {
  return CATEGORY_TRANSLATIONS[name] || translateProductName(name)
}

export function translateAttributeName(name: string): string {
  return ATTRIBUTE_TRANSLATIONS[name] || translateProductName(name)
}

export function translateAttributeValue(value: string): string {
  return ATTRIBUTE_VALUE_TRANSLATIONS[value] || translateProductName(value)
}

// Extended dictionary for industrial/professional drones
const EXTENDED_TERMS: Record<string, string> = {
  'квадрокоптер': 'drone',
  'Квадрокоптер': 'Drone',
  'промышленный': 'industrial',
  'Промышленный': 'Industrial',
  'профессиональный': 'professional',
  'Профессиональный': 'Professional',
  'комплект': 'combo',
  'Комплект': 'Combo',
  'набор': 'kit',
  'Набор': 'Kit',
  'матрица': 'Matrice',
  'Матрица': 'Matrice',
  'зенмуза': 'Zenmuse',
  'Зенмуза': 'Zenmuse',
  'мавик': 'Mavic',
  'Мавик': 'Mavic',
  'фантом': 'Phantom',
  'Фантом': 'Phantom',
  'инспайр': 'Inspire',
  'Инспайр': 'Inspire',
  'аграс': 'Agras',
  'Аграс': 'Agras',
  'максимальный': 'maximum',
  'Максимальный': 'Maximum',
  'время полета': 'flight time',
  'Время полета': 'Flight Time',
  'дальность полета': 'flight range',
  'Дальность полета': 'Flight Range',
  'скорость': 'speed',
  'Скорость': 'Speed',
  'высота': 'altitude',
  'Высота': 'Altitude',
  'грузоподъемность': 'payload capacity',
  'Грузоподъемность': 'Payload Capacity',
  'камера': 'camera',
  'Камера': 'Camera',
  'тепловизор': 'thermal camera',
  'Тепловизор': 'Thermal Camera',
  'зум': 'zoom',
  'Зум': 'Zoom',
  'разрешение': 'resolution',
  'Разрешение': 'Resolution',
  'сенсор': 'sensor',
  'Сенсор': 'Sensor',
  'обнаружение': 'detection',
  'Обнаружение': 'Detection',
  'распознавание': 'recognition',
  'Распознавание': 'Recognition',
  'препятствия': 'obstacles',
  'Препятствия': 'Obstacles',
  'система': 'system',
  'Система': 'System',
  'избегание': 'avoidance',
  'Избегание': 'Avoidance',
  'передача': 'transmission',
  'Передача': 'Transmission',
  'видео': 'video',
  'Видео': 'Video',
  'сигнал': 'signal',
  'Сигнал': 'Signal',
  'частота': 'frequency',
  'Частота': 'Frequency',
  'управление': 'control',
  'Управление': 'Control',
  'пульт': 'remote controller',
  'Пульт': 'Remote Controller',
  'контроллер': 'controller',
  'Контроллер': 'Controller',
  'батарея': 'battery',
  'Батарея': 'Battery',
  'станция': 'station',
  'Станция': 'Station',
  'зарядная': 'charging',
  'Зарядная': 'Charging',
  'зарядка': 'charger',
  'Зарядка': 'Charger',
  'кейс': 'case',
  'Кейс': 'Case',
  'сумка': 'bag',
  'Сумка': 'Bag',
  'пропеллеры': 'propellers',
  'Пропеллеры': 'Propellers',
  'защита': 'protection',
  'Защита': 'Protection',
  'подвес': 'gimbal',
  'Подвес': 'Gimbal',
  'стабилизатор': 'stabilizer',
  'Стабилизатор': 'Stabilizer',
  'RTK': 'RTK',
  'ртк': 'RTK',
  'GPS': 'GPS',
  'гпс': 'GPS',
  'характеристики': 'specifications',
  'Характеристики': 'Specifications',
  'описание': 'description',
  'Описание': 'Description',
  'комплектация': 'package contents',
  'Комплектация': 'Package Contents',
  'в комплекте': 'included',
  'В комплекте': 'Included',
  'входит': 'included',
  'Входит': 'Included',
  'особенности': 'features',
  'Особенности': 'Features',
  'преимущества': 'advantages',
  'Преимущества': 'Advantages',
  'применение': 'applications',
  'Применение': 'Applications',
  'для': 'for',
  'Для': 'For',
  'от': 'from',
  'От': 'From',
  'до': 'to',
  'До': 'To',
  'при': 'at',
  'При': 'At',
  'с': 'with',
  'С': 'With',
  'без': 'without',
  'Без': 'Without',
  'и': 'and',
  'И': 'And',
  'или': 'or',
  'Или': 'Or',
  'не': 'not',
  'Не': 'Not',
  'более': 'more than',
  'Более': 'More Than',
  'менее': 'less than',
  'Менее': 'Less Than',
  'около': 'approximately',
  'Около': 'Approximately',
  'примерно': 'approximately',
  'Примерно': 'Approximately',
  'вес': 'weight',
  'Вес': 'Weight',
  'размер': 'size',
  'Размер': 'Size',
  'длина': 'length',
  'Длина': 'Length',
  'ширина': 'width',
  'Ширина': 'Width',
  'диаметр': 'diameter',
  'Диаметр': 'Diameter',
  'цвет': 'color',
  'Цвет': 'Color',
  'черный': 'black',
  'Черный': 'Black',
  'белый': 'white',
  'Белый': 'White',
  'серый': 'gray',
  'Серый': 'Gray',
  'новый': 'new',
  'Новый': 'New',
  'оригинал': 'original',
  'Оригинал': 'Original',
  'оригинальный': 'original',
  'Оригинальный': 'Original',
  'гарантия': 'warranty',
  'Гарантия': 'Warranty',
  'месяцев': 'months',
  'Месяцев': 'Months',
  'год': 'year',
  'Год': 'Year',
  'лет': 'years',
  'Лет': 'Years',
  'шт': 'pcs',
  'Шт': 'Pcs',
  'штук': 'pieces',
  'Штук': 'Pieces',
  'шт.': 'pcs',
  'в наличии': 'in stock',
  'В наличии': 'In Stock',
  'под заказ': 'to order',
  'Под заказ': 'To Order',
  'доставка': 'delivery',
  'Доставка': 'Delivery',
  'бесплатная': 'free',
  'Бесплатная': 'Free',
  'самовывоз': 'pickup',
  'Самовывоз': 'Pickup',
  'оплата': 'payment',
  'Оплата': 'Payment',
  'цена': 'price',
  'Цена': 'Price',
  'руб': 'RUB',
  'руб.': 'RUB',
  '₽': 'RUB',
  'закажите': 'order',
  'Закажите': 'Order',
  'купить': 'buy',
  'Купить': 'Buy',
  'заказать': 'order',
  'Заказать': 'Order',
  'продажа': 'sale',
  'Продажа': 'Sale',
  'магазин': 'store',
  'Магазин': 'Store',
  'товар': 'product',
  'Товар': 'Product',
  'товары': 'products',
  'Товары': 'Products',
  'все': 'all',
  'Все': 'All',
  'вы': 'you',
  'Вы': 'You',
  'ваш': 'your',
  'Ваш': 'Your',
  'вашего': 'your',
  'вашем': 'your',
  'ваших': 'your',
  'вашей': 'your',
  'найдете': 'will find',
  'найдёте': 'will find',
  'только': 'only',
  'но': 'but',
  'а': 'and',
  'же': 'same',
  'уже': 'already',
  'еще': 'more',
  'ещё': 'more',
  'также': 'also',
  'Также': 'Also',
  'очень': 'very',
  'всего': 'total',
  'можно': 'can',
  'нужно': 'need',
  'необходимо': 'necessary',
  'используется': 'used',
  'Используется': 'Used',
  'используют': 'use',
  'применяется': 'applied',
  'Применяется': 'Applied',
  'помогает': 'helps',
  'Помогает': 'Helps',
  'позволяет': 'allows',
  'Позволяет': 'Allows',
  'обеспечивает': 'provides',
  'Обеспечивает': 'Provides',
  'гарантирует': 'guarantees',
  'Гарантирует': 'Guarantees',
  'создан': 'created',
  'Создан': 'Created',
  'разработан': 'designed',
  'Разработан': 'Designed',
  'предназначен': 'intended',
  'Предназначен': 'Intended',
  'новая': 'new',
  'Новая': 'New',
  'новое': 'new',
  'Новое': 'New',
  'новые': 'new',
  'Новые': 'New',
  'лучший': 'best',
  'Лучший': 'Best',
  'высокий': 'high',
  'Высокий': 'High',
  'высокая': 'high',
  'высокое': 'high',
  'высокие': 'high',
  'низкий': 'low',
  'Низкий': 'Low',
  'большой': 'large',
  'Большой': 'Large',
  'большая': 'large',
  'большое': 'large',
  'большие': 'large',
  'маленький': 'small',
  'Маленький': 'Small',
  'малый': 'small',
  'Малый': 'Small',
  'максимальная': 'maximum',
  'максимальное': 'maximum',
  'максимальные': 'maximum',
  'макс': 'max',
  'Макс': 'Max',
  'минимальный': 'minimum',
  'Минимальный': 'Minimum',
  'дополнительный': 'additional',
  'Дополнительный': 'Additional',
  'дополнительная': 'additional',
  'основной': 'main',
  'Основной': 'Main',
  'основная': 'main',
  'основное': 'main',
  'главный': 'main',
  'Главный': 'Main',
  'дрон': 'drone',
  'Дрон': 'Drone',
  'дрона': 'drone',
  'дронов': 'drones',
  'дроны': 'drones',
  'Дроны': 'Drones',
  'беспилотник': 'UAV',
  'Беспилотник': 'UAV',
  'беспилотника': 'UAV',
  'квадрокоптера': 'quadcopter',
  'промышленная': 'industrial',
  'промышленное': 'industrial',
  'промышленные': 'industrial',
  'профессиональная': 'professional',
  'профессиональное': 'professional',
  'профессиональные': 'professional',
  'профессионал': 'professional',
  'Профессионал': 'Professional',
  'профессионалов': 'professionals',
  'камеры': 'cameras',
  'камерой': 'camera',
  'камеру': 'camera',
  'камерах': 'cameras',
  'фото': 'photo',
  'Фото': 'Photo',
  'фотосъемка': 'photography',
  'съемка': 'shooting',
  'съемки': 'shooting',
  'зума': 'zoom',
  'объектив': 'lens',
  'Объектив': 'Lens',
  'сенсора': 'sensor',
  'сенсоры': 'sensors',
  'сенсоров': 'sensors',
  'мегапиксель': 'megapixel',
  'Мегапиксель': 'Megapixel',
  'мп': 'MP',
  'Мп': 'MP',
  'тепловизионный': 'thermal',
  'Тепловизионный': 'Thermal',
  'тепловизионная': 'thermal',
  'лазерный': 'laser',
  'Лазерный': 'Laser',
  'дальномер': 'rangefinder',
  'Дальномер': 'Rangefinder',
  'гимбл': 'gimbal',
  'Гимбл': 'Gimbal',
  'пропеллер': 'propeller',
  'Пропеллер': 'Propeller',
  'пропеллеров': 'propellers',
  'мотор': 'motor',
  'Мотор': 'Motor',
  'моторы': 'motors',
  'двигатель': 'engine',
  'Двигатель': 'Engine',
  'батареи': 'batteries',
  'батарей': 'batteries',
  'аккумулятор': 'battery',
  'Аккумулятор': 'Battery',
  'аккумулятора': 'battery',
  'аккумуляторы': 'batteries',
  'аккумуляторов': 'batteries',
  'зарядное': 'charger',
  'Зарядное': 'Charger',
  'зарядный': 'charging',
  'передатчик': 'transmitter',
  'Передатчик': 'Transmitter',
  'приемник': 'receiver',
  'Приемник': 'Receiver',
  'антенна': 'antenna',
  'Антенна': 'Antenna',
  'антенны': 'antennas',
  'полет': 'flight',
  'Полет': 'Flight',
  'полета': 'flight',
  'полете': 'flight',
  'полетов': 'flights',
  'полетное': 'flight',
  'полетный': 'flight',
  'полетная': 'flight',
  'дальность': 'range',
  'Дальность': 'Range',
  'дальности': 'range',
  'высоте': 'altitude',
  'высоту': 'altitude',
  'скорости': 'speed',
  'ветер': 'wind',
  'Ветер': 'Wind',
  'ветра': 'wind',
  'ветре': 'wind',
  'нагрузка': 'payload',
  'Нагрузка': 'Payload',
  'нагрузку': 'payload',
  'масса': 'mass',
  'Масса': 'Mass',
  'размеры': 'dimensions',
  'Размеры': 'Dimensions',
  'инспекция': 'inspection',
  'Инспекция': 'Inspection',
  'инспекции': 'inspections',
  'инспекций': 'inspections',
  'мониторинг': 'monitoring',
  'Мониторинг': 'Monitoring',
  'мониторинга': 'monitoring',
  'поиск': 'search',
  'Поиск': 'Search',
  'поиска': 'search',
  'спасение': 'rescue',
  'Спасение': 'Rescue',
  'спасения': 'rescue',
  'картография': 'cartography',
  'Картография': 'Cartography',
  'строительство': 'construction',
  'Строительство': 'Construction',
  'энергетика': 'energy',
  'Энергетика': 'Energy',
  'нефть': 'oil',
  'газ': 'gas',
  'сельское': 'agricultural',
  'сельское хозяйство': 'agriculture',
  'пожарный': 'fire',
  'Пожарный': 'Fire',
  'пожар': 'fire',
  'Пожар': 'Fire',
  'безопасность': 'safety',
  'Безопасность': 'Safety',
  'надежность': 'reliability',
  'Надежность': 'Reliability',
  'точность': 'accuracy',
  'Точность': 'Accuracy',
  'эффективность': 'efficiency',
  'Эффективность': 'Efficiency',
  'производительность': 'performance',
  'Производительность': 'Performance',
  'системы': 'systems',
  'системой': 'system',
  'систему': 'system',
  'системах': 'systems',
  'технология': 'technology',
  'Технология': 'Technology',
  'технологии': 'technology',
  'технологий': 'technologies',
  'функция': 'function',
  'Функция': 'Function',
  'функции': 'functions',
  'функций': 'functions',
  'режим': 'mode',
  'Режим': 'Mode',
  'режиме': 'mode',
  'режимы': 'modes',
  'управления': 'control',
  'управлении': 'control',
  'навигация': 'navigation',
  'Навигация': 'Navigation',
  'позиционирование': 'positioning',
  'Позиционирование': 'Positioning',
  'позиционирования': 'positioning',
  'обнаружения': 'detection',
  'препятствие': 'obstacle',
  'Препятствие': 'Obstacle',
  'препятствий': 'obstacles',
  'облета': 'avoidance',
  'защиты': 'protection',
  'IP45': 'IP45',
  'IP55': 'IP55',
  'водонепроницаемый': 'waterproof',
  'пылезащищенный': 'dustproof',
  'температура': 'temperature',
  'Температура': 'Temperature',
  'температур': 'temperatures',
  'рабочая': 'operating',
  'рабочих': 'operating',
  'диапазон': 'range',
  'Диапазон': 'Range',
  'передачи': 'transmission',
  'сигнала': 'signal',
  'канал': 'channel',
  'Канал': 'Channel',
  'каналов': 'channels',
  'частоте': 'frequency',
  'частот': 'frequencies',
  'ГГц': 'GHz',
  'ггц': 'GHz',
  'МГц': 'MHz',
  'км': 'km',
  'км/ч': 'km/h',
  'м/с': 'm/s',
  'м': 'm',
  'см': 'cm',
  'мм': 'mm',
  'кг': 'kg',
  'г': 'g',
  'мин': 'min',
  'сек': 'sec',
  'ч': 'h',
  'В': 'V',
  'А': 'A',
  'Вт': 'W',
  'Вт·ч': 'Wh',
  'умный': 'smart',
  'Умный': 'Smart',
  'умная': 'smart',
  'интеллектуальный': 'intelligent',
  'Интеллектуальный': 'Intelligent',
  'интеллектуальная': 'intelligent',
  'интеллектуальные': 'intelligent',
  'автоматический': 'automatic',
  'Автоматический': 'Automatic',
  'автоматическая': 'automatic',
  'автоматические': 'automatic',
  'автономный': 'autonomous',
  'Автономный': 'Autonomous',
  'цифровой': 'digital',
  'Цифровой': 'Digital',
  'цифровая': 'digital',
  'оптический': 'optical',
  'Оптический': 'Optical',
  'оптическая': 'optical',
  'цифровой зум': 'digital zoom',
  'оптический зум': 'optical zoom',
  'широкоугольный': 'wide-angle',
  'Широкоугольный': 'Wide-angle',
  'со': 'with',
  'в': 'in',
  'во': 'in',
  'на': 'on',
  'На': 'On',
  'над': 'above',
  'под': 'under',
  'Под': 'Under',
  'за': 'behind',
  'За': 'Behind',
  'перед': 'in front of',
  'Перед': 'In front of',
  'через': 'through',
  'Через': 'Through',
  'между': 'between',
  'Между': 'Between',
  'вокруг': 'around',
  'Вокруг': 'Around',
  'внутри': 'inside',
  'Внутри': 'Inside',
  'снаружи': 'outside',
  'к': 'to',
  'К': 'To',
  'по': 'by',
  'По': 'By',
  'из': 'from',
  'Из': 'From',
  'об': 'about',
  'Об': 'About',
  'о': 'about',
  'О': 'About',
  'который': 'which',
  'которая': 'which',
  'которое': 'which',
  'которые': 'which',
  'где': 'where',
  'Где': 'Where',
  'когда': 'when',
  'Когда': 'When',
  'как': 'how',
  'Как': 'How',
  'что': 'that',
  'Что': 'What',
  'чтобы': 'to',
  'этот': 'this',
  'Этот': 'This',
  'эта': 'this',
  'Это': 'This',
  'это': 'this',
  'эти': 'these',
  'Эти': 'These',
  'тот': 'that',
  'Тот': 'That',
  'та': 'that',
  'те': 'those',
  'Те': 'Those',
  'такой': 'such',
  'Такой': 'Such',
  'такая': 'such',
  'один': 'one',
  'Один': 'One',
  'одна': 'one',
  'одно': 'one',
  'два': 'two',
  'Два': 'Two',
  'две': 'two',
  'три': 'three',
  'Три': 'Three',
  'четыре': 'four',
  'Четыре': 'Four',
  'пять': 'five',
  'Пять': 'Five',
  'шесть': 'six',
  'Шесть': 'Six',
  'семь': 'seven',
  'Семь': 'Seven',
  'восемь': 'eight',
  'девять': 'nine',
  'десять': 'ten',
  'первый': 'first',
  'Первый': 'First',
  'второй': 'second',
  'Второй': 'Second',
  'третий': 'third',
  'Третий': 'Third',
  'технические': 'technical',
  'Технические': 'Technical',
  'отзывы': 'reviews',
  'Отзывы': 'Reviews',
  'похожие': 'related',
  'Похожие': 'Related',
  'рекомендуемые': 'recommended',
  'Рекомендуемые': 'Recommended',
  'аксессуары': 'accessories',
  'Аксессуары': 'Accessories',
  'запчасти': 'spare parts',
  'Запчасти': 'Spare Parts',
  'ремешок': 'strap',
  'кабель': 'cable',
  'Кабель': 'Cable',
  'кабели': 'cables',
  'адаптер': 'adapter',
  'Адаптер': 'Adapter',
  'зарядное устройство': 'charger',
  'состояние': 'condition',
  'Состояние': 'Condition',
  'гарантии': 'warranty',
  'подделка': 'counterfeit',
  'сертифицированный': 'certified',
  'Сертифицированный': 'Certified',
  'быстрая доставка': 'fast delivery',
  'Быстрая доставка': 'Fast Delivery',
  'бесплатная доставка': 'free shipping',
  'Бесплатная доставка': 'Free Shipping',
  'оптом': 'wholesale',
  'Оптом': 'Wholesale',
  'в розницу': 'retail',
  'скидка': 'discount',
  'Скидка': 'Discount',
  'скидки': 'discounts',
  'распродажа': 'sale',
  'Распродажа': 'Sale',
  'акция': 'promotion',
  'Акция': 'Promotion',
  'поддерживает': 'supports',
  'Поддерживает': 'Supports',
  'поддержка': 'support',
  'Поддержка': 'Support',
  'включает': 'includes',
  'Включает': 'Includes',
  'содержит': 'contains',
  'имеет': 'has',
  'Имеет': 'Has',
  'обладает': 'features',
  'Обладает': 'Features',
  'оснащен': 'equipped',
  'Оснащен': 'Equipped',
  'оснащена': 'equipped',
  'оборудован': 'equipped',
  'Оборудован': 'Equipped',
  'совместим': 'compatible',
  'Совместим': 'Compatible',
  'совместима': 'compatible',
  'работает': 'works',
  'Работает': 'Works',
  'функционирует': 'operates',
  'запускается': 'starts',
  'включается': 'turns on',
  'выключается': 'turns off',
  'устройство': 'device',
  'Устройство': 'Device',
  'устройства': 'devices',
  'устройств': 'devices',
  'оборудование': 'equipment',
  'Оборудование': 'Equipment',
  'модель': 'model',
  'Модель': 'Model',
  'модели': 'models',
  'версия': 'version',
  'Версия': 'Version',
  'версии': 'versions',
  'производитель': 'manufacturer',
  'Производитель': 'Manufacturer',
  'бренд': 'brand',
  'Бренд': 'Brand',
  'бренды': 'brands',
  'Бренды': 'Brands',
  'категория': 'category',
  'Категория': 'Category',
  'категории': 'categories',
  'Категории': 'Categories',
  'тип': 'type',
  'Тип': 'Type',
  'типа': 'type',
  'вид': 'kind',
  'Вид': 'Kind',
  'нет': 'no',
  'Нет': 'No',
  'нельзя': 'cannot',
  'невозможно': 'impossible',
  'отсутствует': 'missing',
  'Отсутствует': 'Missing',
  'время': 'time',
  'Время': 'Time',
  'день': 'day',
  'День': 'Day',
  'дня': 'days',
  'дней': 'days',
  'час': 'hour',
  'Час': 'Hour',
  'часа': 'hours',
  'часов': 'hours',
  'минута': 'minute',
  'Минута': 'Minute',
  'минут': 'minutes',
  'секунда': 'second',
  'секунд': 'seconds',
  'года': 'years',
  'месяц': 'month',
  'Месяц': 'Month',
  'неделя': 'week',
  'Неделя': 'Week',
  'место': 'place',
  'Место': 'Place',
  'зона': 'zone',
  'Зона': 'Zone',
  'область': 'area',
  'Область': 'Area',
  'регион': 'region',
  'Регион': 'Region',
  'страна': 'country',
  'Страна': 'Country',
  'город': 'city',
  'Город': 'City',
  'стоимость': 'cost',
  'Стоимость': 'Cost',
  'количество': 'quantity',
  'Количество': 'Quantity',
  'комплекты': 'kits',
  'полетный контроллер': 'flight controller',
  'Полетный контроллер': 'Flight Controller',
  'плата управления': 'control board',
  'рама': 'frame',
  'Рама': 'Frame',
  'рамы': 'frames',
  'корпус': 'body',
  'Корпус': 'Body',
  'шасси': 'landing gear',
  'Шасси': 'Landing Gear',
  'посадочное': 'landing',
  'ноги': 'legs',
  'винты': 'propellers',
  'Винты': 'Propellers',
  'лопасти': 'blades',
  'Лопасти': 'Blades',
  'Моторы': 'Motors',
  'ESC': 'ESC',
  'регулятор скорости': 'speed controller',
  'Регулятор скорости': 'Speed Controller',
  'плата распределения': 'power distribution board',
  'питание': 'power',
  'Питание': 'Power',
  'напряжение': 'voltage',
  'Напряжение': 'Voltage',
  'ток': 'current',
  'Ток': 'Current',
  'мощность': 'power',
  'Мощность': 'Power',
  'емкость': 'capacity',
  'Емкость': 'Capacity',
  'LiPo': 'LiPo',
  'Li-ion': 'Li-ion',
  'литий-полимерный': 'lithium polymer',
  'зарядная станция': 'charging station',
  'Зарядная станция': 'Charging Station',
  'хаб': 'hub',
  'Хаб': 'Hub',
  'камера с зумом': 'zoom camera',
  'широкоугольная камера': 'wide camera',
  'основная камера': 'main camera',
  'Основная камера': 'Main Camera',
  'дополнительная камера': 'additional camera',
  'ночное видение': 'night vision',
  'Ночное видение': 'Night Vision',
  'инфракрасный': 'infrared',
  'Инфракрасный': 'Infrared',
  'ИК': 'IR',
  'тепловизионная камера': 'thermal camera',
  'Тепловизионная камера': 'Thermal Camera',
  'лазерный дальномер': 'laser rangefinder',
  'приложение': 'application',
  'Приложение': 'Application',
  'программа': 'software',
  'Программа': 'Software',
  'программное обеспечение': 'software',
  'ПО': 'software',
  'прошивка': 'firmware',
  'Прошивка': 'Firmware',
  'обновление': 'update',
  'Обновление': 'Update',
  'обновления': 'updates',
  'DJI Pilot': 'DJI Pilot',
  'DJI FlightHub': 'DJI FlightHub',
  'DJI Terra': 'DJI Terra',
  'вершина': 'pinnacle',
  'Вершина': 'Pinnacle',
  'сложнейших': 'most complex',
  'миссий': 'missions',
  'Миссий': 'Missions',
  'миссии': 'missions',
  'Миссии': 'Missions',
  'нужна': 'needed',
  'назначение': 'purpose',
  'Назначение': 'Purpose',
  'критической': 'critical',
  'инфраструктуры': 'infrastructure',
  'Инфраструктуры': 'Infrastructure',
  'незаменим': 'indispensable',
  'Незаменим': 'Indispensable',
  'энергетиков': 'energy workers',
  'ЛЭП': 'power lines',
  'лэп': 'power lines',
  'подстанции': 'substations',
  'подстанций': 'substations',
  'ветропарки': 'wind farms',
  'обследования': 'surveying',
  'вышек': 'towers',
  'связи': 'communication',
  'промышленных': 'industrial',
  'объектов': 'objects',
  'службы': 'services',
  'Службы': 'Services',
  'доверяют': 'trust',
  'людей': 'people',
  'днем': 'during the day',
  'ночью': 'at night',
  'видит': 'sees',
  'сквозь': 'through',
  'дым': 'smoke',
  'полной': 'complete',
  'темноте': 'darkness',
  'строительстве': 'construction',
  'масштабных': 'large-scale',
  'пожарным': 'firefighters',
  'оценивать': 'assess',
  'очаги': 'sources',
  'возгорания': 'fire',
  'безопасно': 'safely',
  'экологического': 'environmental',
  'универсальное': 'universal',
  'решение': 'solution',
  'Решение': 'Solution',
  'самых': 'most',
  'ответственных': 'responsible',
  'операций': 'operations',
  'Операций': 'Operations',
  'мощь': 'power',
  'универсальность': 'versatility',
  'платформа': 'platform',
  'Платформа': 'Platform',
  'флагманская': 'flagship',
  'Флагманская': 'Flagship',
  'защитой': 'protection',
  'сильном': 'strong',
  'дожде': 'rain',
  'от -20': 'from -20',
  '+50': '+50',
  'несет': 'carries',
  'полезную': 'payload',
  'шестью': 'six',
  'интеллектуальными': 'intelligent',
  'батареями': 'batteries',
  'TB60': 'TB60',
  'горячей': 'hot',
  'замены': 'swap',
  'поле': 'field',
  'HD-видео': 'HD video',
  'OcuSync': 'OcuSync',
  'Enterprise': 'Enterprise',
  'гибридная': 'hybrid',
  'объединяет': 'combines',
  'одном': 'one',
  'оптическим': 'optical',
  'зумом': 'zoom',
  '23х': '23x',
  '23×': '23x',
  'широкоугольная': 'wide-angle',
  'полем': 'field',
  'зрения': 'view',
  '84°': '84°',
  'точностью': 'accuracy',
  '1200': '1200',
  '640×512': '640×512',
  'px': 'px',
  '30': '30',
  'Гц': 'Hz',
  'снимают': 'capture',
  'одновременно': 'simultaneously',
  'картины': 'picture',
  'координатная': 'coordinate',
  'привязка': 'tagging',
  'данных': 'data',
  'сантиметровой': 'centimeter',
  'встроенная': 'built-in',
  'PPK': 'PPK',
  'точного': 'precise',
  'APAS': 'APAS',
  '5.0': '5.0',
  '360°': '360°',
  'шестикратное': 'six-fold',
  'резервирование': 'redundancy',
  'датчиков': 'sensors',
  'FlightAutonomy': 'FlightAutonomy',
  'двойных': 'dual',
  'операторов': 'operators',
  'пилот': 'pilot',
  'специалист': 'specialist',
  'RC': 'RC',
  'Plus': 'Plus',
  'наземной': 'ground',
  'станцией': 'station',
  'D-RTK': 'D-RTK',
  'Mobile': 'Mobile',
  'интеграция': 'integration',
  'парком': 'fleet',
  'ключевые': 'key',
  'комплекта': 'kit',
  'непревзойденная': 'unmatched',
  'работа': 'operation',
  'экстремальных': 'extreme',
  'условиях': 'conditions',
  'рекордное': 'record',
  '55': '55',
  'сложных': 'complex',
  'всевидящая': 'all-seeing',
  'модуле': 'module',
  'полного': 'complete',
  'анализа': 'analysis',
  'сантиметровая': 'centimeter-level',
  'измерений': 'measurements',
  'картографии': 'mapping',
  'систем': 'systems',
  'эффективное': 'effective',
  'двойные': 'dual',
  'прочность': 'durability',
  'ежедневных': 'daily',
  'интенсивных': 'intensive',
  'задач': 'tasks',
  'кит': 'kit',
  'абсолютный': 'absolute',
  'лидер': 'leader',
  'классе': 'class',
  'полный': 'full',
  'обзор': 'overview',
  'любой': 'any',
  'ситуации': 'situation',
  'будь': 'whether',
  'ночной': 'night',
  'напряжением': 'voltage',
  'опасного': 'dangerous',
  'объекта': 'object',
  'нашем': 'our',
  'магазине': 'store',
  'сам': 'the',
  'комбо': 'combo',
  'M300': 'M300',
  'H20T': 'H20T',
  'бесперебойной': 'uninterrupted',
  'работы': 'operation',
  'оригинальные': 'original',
  'мощные': 'powerful',
  'зарядные': 'charging',
  'станции': 'stations',
  'BS60': 'BS60',
  'Intelligent': 'Intelligent',
  'Battery': 'Battery',
  'запасные': 'spare',
  'части': 'parts',
  'посадочные': 'landing',
  'пульты': 'remotes',
  'карты': 'cards',
  'памяти': 'memory',
  'специализированные': 'specialized',
  'защитные': 'protective',
  'кейсы': 'cases',
  'обеспечьте': 'ensure',
  'флот': 'fleet',
  'надежными': 'reliable',
  'комплектующими': 'components',
  'COPTERPARTS': 'AEGISKY',
  'выполняйте': 'perform',
  'абсолютной': 'absolute',
  'уверенностью': 'confidence',
  'используя': 'using',
  'всевидящее': 'all-seeing',
  'око': 'eye',
  'раскройте': 'unleash',
  'безграничные': 'limitless',
  'возможности': 'capabilities',
  'промышленной': 'industrial',
  'аэросъемки': 'aerial photography',
  'успейте': 'hurry',
  'сниженной': 'reduced',
  'цене': 'price',
  'коммерческая': 'commercial',
  'создание': 'creation',
  'которой': 'which',
  'DJI': 'DJI',
  'вдохновили': 'inspired',
  'современные': 'modern',
  'авиационные': 'aviation',
  'летательного': 'flying',
  'аппарата': 'vehicle',
  'составляет': 'is',
  'он': 'it',
  'предлагает': 'offers',
  'расширенные': 'advanced',
  'искусственного': 'artificial',
  'интеллекта': 'intelligence',
  'ИИ': 'AI',
  '6': '6',
  'направлениях': 'directions',
  'ведь': 'because',
  'сочетает': 'combines',
  'высокой': 'high',
  'производительностью': 'performance',
  'непревзойденной': 'unmatched',
  'задает': 'sets',
  'стандарт': 'standard',
  'качества': 'quality',
  'трансмиссия': 'transmission',
  '15': '15',
  'детектирование': 'detection',
  'дисплей': 'display',
  'полетных': 'flight',
  'уровня': 'level',
  'горячая': 'hot',
  'замена': 'swap',
  'состоянием': 'status',
  'БПЛА': 'UAV',
  'усовершенствованная': 'advanced',
  'расстоянии': 'distance',
  'трехканальную': 'three-channel',
  'передачу': 'transmission',
  'разрешении': 'resolution',
  '1080p': '1080p',
  'автопереключение': 'auto-switching',
  'частотами': 'frequencies',
  '2,4': '2.4',
  '5,8': '5.8',
  'увеличивает': 'increases',
  'областях': 'areas',
  'сильными': 'strong',
  'помехами': 'interference',
  'алгоритм': 'algorithm',
  'шифрования': 'encryption',
  'AES-256': 'AES-256',
  'передавать': 'transmit',
  'данные': 'data',
  'трехканальная': 'three-channel',
  'реального': 'real',
  'времени': 'time',
  'улучшенные': 'improved',
  'полетные': 'flight',
  'силовая': 'power',
  'установка': 'unit',
  'усовершенствованными': 'advanced',
  'характеристиками': 'specifications',
  'повышают': 'improve',
  'стабильность': 'stability',
  'даже': 'even',
  'суровых': 'harsh',
  'снижения': 'descent',
  'допустимая': 'allowable',
  'разнообразие': 'variety',
  'конфигураций': 'configurations',
  'настройте': 'configure',
  'так': 'so',
  'решения': 'solutions',
  'устанавливайте': 'install',
  '3': '3',
  'максимальной': 'maximum',
  'массой': 'mass',
  '2,7': '2.7',
  'запись': 'recording',
  'реальном': 'real',
  'записывайте': 'record',
  'действия': 'actions',
  'выполняемые': 'performed',
  'ходу': 'course',
  'маршрута': 'route',
  'движение': 'movement',
  'положение': 'position',
  'стабилизатора': 'gimbal',
  'увеличение': 'zoom',
  'изображения': 'image',
  'после': 'after',
  'этого': 'this',
  'сможете': 'can',
  'создать': 'create',
  'файлы': 'files',
  'готовыми': 'ready',
  'маршрутами': 'routes',
  'применять': 'apply',
  'их': 'them',
  'автоматических': 'automatic',
  'выборочная': 'selective',
  'проверка': 'inspection',
  'помощью': 'using',
  'автоматизируйте': 'automate',
  'получайте': 'get',
  'стабильные': 'stable',
  'результаты': 'results',
  'бортовой': 'onboard',
  'распознает': 'recognizes',
  'объект': 'object',
  'находит': 'finds',
  'его': 'it',
  'последующих': 'subsequent',
  'автоматизированных': 'automated',
  'задачах': 'tasks',
  'таким': 'thus',
  'образом': 'way',
  'цель': 'target',
  'всегда': 'always',
  'будет': 'will',
  'оставаться': 'remain',
  'кадре': 'frame',
  'точкам': 'waypoints',
  '2.0': '2.0',
  'создавайте': 'create',
  '65535': '65535',
  'точек': 'points',
  'задавайте': 'set',
  'выполнения': 'execution',
  'точках': 'points',
  'одним': 'one',
  'несколькими': 'multiple',
  'устройствами': 'devices',
  'том': 'including',
  'числе': 'number',
  'сторонних': 'third-party',
  'производителей': 'manufacturers',
  'планирование': 'planning',
  'оптимизировано': 'optimized',
  'увеличения': 'increasing',
  'гибкости': 'flexibility',
  'эффективности': 'efficiency',
  'интеллектуальное': 'intelligent',
  'следование': 'following',
  // Additional drone tech terms batch 2
  'мультисенсорной': 'multisensor',
  'мультисенсорная': 'multisensor',
  'вершина': 'flagship',
  'сложнейших': 'most complex',
  'создан': 'designed',
  'критической': 'critical',
  'инфраструктуры': 'infrastructure',
  'энергетиков': 'power utilities',
  'лэп': 'power lines',
  'подстанции': 'substations',
  'ветропарки': 'wind farms',
  'обследования': 'inspection',
  'вышек': 'towers',
  'службы': 'services',
  'спасения': 'rescue',
  'доверяют': 'trust',
  'поиск': 'search',
  'людей': 'people',
  'дым': 'smoke',
  'темноте': 'darkness',
  'строительстве': 'construction',
  'масштабных': 'large-scale',
  'объектов': 'sites',
  'пожарным': 'firefighters',
  'очаги': 'sources',
  'возгорания': 'fire',
  'экологического': 'environmental',
  'картографии': 'mapping',
  'универсальное': 'versatile',
  'решение': 'solution',
  'мощь': 'power',
  'платформа': 'platform',
  'флагманская': 'flagship',
  'сильном': 'strong',
  'ветре': 'winds',
  'дожде': 'rain',
  'несет': 'carries',
  'полезную': 'payload',
  'нагрузку': 'capacity',
  'интеллектуальными': 'intelligent',
  'батареями': 'batteries',
  'горячей': 'hot-swap',
  'поле': 'field',
  'передачи': 'transmission',
  'гибридная': 'hybrid',
  'объединяет': 'integrates',
  'оптическим': 'optical',
  'зумом': 'zoom',
  'широкоугольная': 'wide-angle',
  'зрения': 'view',
  'лазерный': 'laser',
  'дальномер': 'rangefinder',
  'точностью': 'accuracy',
  'тепловизионный': 'thermal',
  'картины': 'overview',
  'координация': 'coordination',
  'интеллектуальные': 'intelligent',
  'точного': 'precise',
  'позиционирования': 'positioning',
  'облета': 'obstacle',
  'препятствий': 'avoidance',
  'шестикратное': 'six-direction',
  'резервирование': 'redundancy',
  'двойных': 'dual',
  'операторов': 'operators',
  'пилот': 'pilot',
  'специалист': 'specialist',
  'наземной': 'ground',
  'станцией': 'station',
  'интеграция': 'integration',
  'парком': 'fleet',
  'рекордное': 'record-breaking',
  'инспекций': 'inspections',
  'измерений': 'measurements',
  'прочность': 'durability',
  'ежедневных': 'daily',
  'интенсивных': 'intensive',
  'задач': 'missions',
  'абсолютный': 'absolute',
  'лидер': 'leader',
  'любую': 'any',
  'ситуацию': 'situation',
  'будь': 'whether',
  'ночной': 'night',
  'напряжением': 'voltage',
  'опасного': 'hazardous',
  'магазине': 'store',
  'бесперебойной': 'uninterrupted',
  'работы': 'operation',
  'оригинальные': 'original',
  'мощные': 'high-power',
  'зарядные': 'charging',
  'станции': 'stations',
  'миссии': 'missions',
  'обнаружения': 'detection',
  'сигналов': 'signals',
  'данных': 'data',
  'специализированные': 'specialized',
}

// Merge all terms
const ALL_TERMS: Record<string, string> = {
  ...TECH_TERMS,
  ...EXTENDED_TERMS,
}

// Build lookup maps for fast translation
const TERM_SORTED = Object.entries(ALL_TERMS).sort((a, b) => b[0].length - a[0].length)
const TERM_MAP = new Map<string, string>()
TERM_SORTED.forEach(([ru, en]) => {
  TERM_MAP.set(ru.toLowerCase(), en)
})

// Build exact match lookup
const EXACT_LOOKUP = new Map<string, string>()
;[...Object.entries(CATEGORY_TRANSLATIONS), ...Object.entries(ATTRIBUTE_TRANSLATIONS), 
 ...Object.entries(ATTRIBUTE_VALUE_TRANSLATIONS), ...Object.entries(EXTENDED_TERMS),
 ...Object.entries(TECH_TERMS)].forEach(([k, v]) => {
  EXACT_LOOKUP.set(k.toLowerCase(), v)
})

/**
 * Translate text content using word-by-word replacement (optimized)
 */
export function translateText(text: string): string {
  if (!text) return text

  // Try exact match first (case-insensitive)
  const exact = EXACT_LOOKUP.get(text.toLowerCase())
  if (exact) return exact

  // Split text into words and translate each word
  // This is faster than complex regex for large dictionaries
  return text.replace(/[а-яА-ЯёЁ]+(?:\s+[а-яА-ЯёЁ]+)*/g, (match) => {
    const lower = match.toLowerCase()
    // Try multi-word match first
    const translated = TERM_MAP.get(lower)
    if (translated) {
      // Preserve capitalization of first letter
      if (match[0] === match[0].toUpperCase()) {
        return translated.charAt(0).toUpperCase() + translated.slice(1)
      }
      return translated
    }
    // Try single word match (split by spaces)
    const words = match.split(/\s+/)
    const translatedWords = words.map(word => {
      const w = word.toLowerCase()
      const t = TERM_MAP.get(w)
      if (t) {
        if (word[0] === word[0].toUpperCase()) {
          return t.charAt(0).toUpperCase() + t.slice(1)
        }
        return t
      }
      return word
    })
    return translatedWords.join(' ')
  })
}

/**
 * Translate HTML content while preserving tags
 */
export function translateHtmlContent(html: string): string {
  if (!html) return html

  let result = html

  // Remove script and style tags content (keep tags but empty them)
  result = result.replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '<script></script>')
  result = result.replace(/<style[^>]*>[\s\S]*?<\/style>/gi, '<style></style>')

  // Fix video tags: convert <video><a href="url.mp4">url</a></video> to proper HTML5 video
  result = result.replace(/<video([^>]*)>([\s\S]*?)<\/video>/gi, (match, attrs, inner) => {
    // Extract video URL from href
    const hrefMatch = inner.match(/href=["']([^"']+\.(?:mp4|webm|mov))["']/i)
    if (hrefMatch) {
      const videoUrl = hrefMatch[1]
      // Ensure controls attribute
      const videoAttrs = attrs.includes('controls') ? attrs : attrs + ' controls'
      const widthMatch = videoAttrs.match(/width=["']?(\d+)/i)
      const width = widthMatch ? widthMatch[1] : '640'
      return `<div class="video-wrapper" style="position:relative;max-width:100%;margin:1rem 0;"><video${videoAttrs} style="max-width:100%;height:auto;border-radius:8px;background:#000;" preload="metadata" playsinline><source src="${videoUrl}" type="video/mp4" />Your browser does not support the video tag. <a href="${videoUrl}" target="_blank" rel="noopener">Download video</a></video></div>`
    }
    return match
  })

  // Check if content has significant Cyrillic
  const cyrillicCount = (result.match(/[\u0400-\u04FF]/g) || []).length
  if (cyrillicCount < 5) return result // Skip if mostly already English

  // Translate text between tags
  // Match text nodes (content between > and < that contains non-whitespace)
  result = result.replace(/>([^<]+)</g, (match, textContent) => {
    const trimmed = textContent.trim()
    if (!trimmed) return match
    // Skip if it's just numbers, punctuation, or already English
    if (/^[\d\s.,;:!?()\-–—_+=*/\\|@#$%^&<>[\]{}"'`~]+$/.test(trimmed)) return match
    if (!/[\u0400-\u04FF]/.test(trimmed)) return match
    // Skip URLs
    if (/^https?:\/\//i.test(trimmed)) return match
    const translated = translateText(trimmed)
    return '>' + textContent.replace(trimmed, translated) + '<'
  })

  // Translate alt and title attributes
  result = result.replace(/\b(alt|title|placeholder)="([^"]*[\u0400-\u04FF][^"]*)"/gi, (match, attr, value) => {
    return `${attr}="${translateText(value)}"`
  })

  return result
}
